/*
 * This file contains the implementation of virtual FIFO
 * Submodules in this file:
 *      Data selector
 *      Fifo entry
 *      Fifo
 */

#include "virtual_fifo.hpp"
#include "top_modules.hpp"

/*
 * This function generates the data select signal for each fifo index
 *
 * param[in] input      FIFO update input signal which contains new job id and new job index
 * param[in] pop_input  Pop signal to the FIFO
 * param[in] fifo_index Index in the FIFO for which the data select signal needs to be implemented
 * 
 * param[out] data_select_signal    Data selector signal for the specified fifo index
 */

void data_selector_per_index(fifo_update_input_t input, one_bit_t pop_input, vf_index_t fifo_index,
                                  data_selector_t *data_select_signal) {

    //#pragma HLS pipeline
    //check if there is a new job added to the FIFO
    if (input.new_job_id != INVALID_JOB_ID) {
        
        //check if there is pop operation
        if (pop_input == 1) {
            // the new job goes into index 0 or 1 i.e becomes the top job
            if (input.fifo_index <= 1) {
                if (fifo_index == 0) {
                    *data_select_signal = NEW_D_SELECT;
                } else {
                    *data_select_signal = W_DISABLE;
                }
            } else {
                //if the current index is less than new job's index, just do left shift
                if (fifo_index < (input.fifo_index - 1)) {
                    *data_select_signal = LD_SELECT;
                } else if (fifo_index == (input.fifo_index - 1)) {
                    //current index is same as new index, select new data
                    *data_select_signal = NEW_D_SELECT;
                } else {
                    //current index is after the new index, so write disable 
                    *data_select_signal = W_DISABLE;
                }
            }
        } else {
            //no pop operation
            //right shift all the data from the new index + 1 to the last entry
            //select new data for the new index
            if (fifo_index < input.fifo_index) {
                *data_select_signal = W_DISABLE;
            } else if (fifo_index == input.fifo_index) {
                //current index is same as new index, select new data
                *data_select_signal = NEW_D_SELECT;
            } else {
                //current index is after the new index, so write disable 
                *data_select_signal = RD_SELECT;
            }
        }

    } else {
        //no new job received, check for pop
        if (pop_input == 1) {
            *data_select_signal = LD_SELECT;
        } else {
            *data_select_signal = W_DISABLE;
        }
    }
}

/*
 * This function implements the data selector that generates the data
 * selector signals for each register in the fifo
 * 
 * param[in] input  Input to the data selector
 * param[out] data_select_signals   Data selection signals generated
 */
void data_selector(fifo_update_input_t input, one_bit_t pop_input, data_selector_t *data_select_signals) {
    
vf_ds_loop:
    for (vf_index_t fifo_index = 0; fifo_index < JOBS_PER_MACHINE; fifo_index++) {
        //#pragma HLS UNROLL
        data_selector_per_index(input, pop_input, fifo_index, &data_select_signals[fifo_index]);
    }
}

/*
 * This function implements data_selector module for all machines
 */
void data_selector_all_machines(fifo_update_input_t *input, 
                                one_bit_t *pop_input, 
                                data_selector_t data_select_signals[NUM_MACHINES][JOBS_PER_MACHINE],
                                fifo_update_input_t *input_temp, 
                                one_bit_t *pop_input_temp) {

ds_all_machines:
    for (machine_id_t machine = 0; machine < NUM_MACHINES; machine++) {
        //#pragma HLS UNROLL
        data_selector(input[machine], pop_input[machine], data_select_signals[machine]);
        input_temp[machine] = input[machine];
        pop_input_temp[machine] = pop_input[machine];
    }

}

/*
 * This function implements register to be used in the virtual FIFO
 * 
 * param[in] left_data   Data from the left neighbor 
 * param[in] right_data  Data from the right neighbor
 * param[in] new_data    New job index
 * param[in] data_select Data select signal generated by data_selector
 * 
 * param[out] out_data       Data stored in the register
 */
void fifo_register(job_id_t left_data, job_id_t right_data, job_id_t new_data, 
                   job_id_t current_data, data_selector_t data_selector,  
                   job_id_t *out_data) {

    //check for write disable
    if (data_selector == LD_SELECT) {
        *out_data = left_data;
    } else if (data_selector == RD_SELECT) {
        *out_data = right_data;
    } else if (data_selector == NEW_D_SELECT) {
        *out_data = new_data;
    } else {
        *out_data = current_data;
    }
}

/*
 * This function implements the fifo
 *
 * param[in] new_job_id              ID of the new job
 * param[in] pop                     Control signal indicating whether to pop the fifo
 * param[in] data_select_signals     Array of data select signals from data selector
 * param[in] fifo_registers_previous Previous cycle FIFO contents
 * param[in] reset                   Reset signal to the fifos
 * 
 * param[out] fifo_registers_current Fifo contents at the end of current cycle
 * param[out] top_job_id             ID of the job at the top of the FIFO
 * param[out] popped_job_id          ID of the popped job from the FIFO
 * param[out] fifo_entry_count       Number of valid jobs in the FIFO
 * param[out] full                   Signal indicating that the fifo is full
 */
void fifo(job_id_t new_job_id, one_bit_t pop, data_selector_t *data_select_signals,
          job_id_t *fifo_registers_current, job_id_t* fifo_registers_previous,
          //one_bit_t *reset, - Not needed until INVALID_JOB_ID is not zero
          job_id_t *fifo_entry_count, 
          job_id_t* top_job_id, job_id_t* popped_job_id,
          one_bit_t* full) {
    /*
     * Note: This function cannot be pipelined
     * fifo_register_previous has Write after Read and this hazard cannot be removed
     * fifo_register_previous should not be written until all fifo_register_current are updated
     * Hence, two separate loops for fifo_write and fifo_read are required. 
     * 
     * CAUTION: DO NOT MERGE fifo_write AND fifo_read LOOPS. IT WILL LEAD TO INCONSISTENCIES
     * 
     * Similary fifo_reset loop cannot be merged with any other loops as all the values in fifo_registers_previous
     * should be updated before read. The loop is currently commented out because INVALID_JOB_ID is zero and 
     * static keyword initializes all the entries to zero. ENABLE THE fifo_reset LOOP WHEN INVALID_JOB_ID IS ANYTHING
     * OTHER THAN 0
     */
    
    /*
    if (*reset == 0) {
fifo_reset: for (vf_index_t fifo_index = 0; fifo_index < JOBS_PER_MACHINE; fifo_index++) {
                //#pragma HLS UNROLL
                fifo_registers_current[fifo_index]  = INVALID_JOB_ID;
                fifo_registers_previous[fifo_index] = INVALID_JOB_ID;
            }
            *reset = 1;
    }
    */

fifo_write: for (vf_index_t fifo_index = 0; fifo_index < JOBS_PER_MACHINE; fifo_index++) {
        //#pragma HLS UNROLL

        if (fifo_index == 0) {
            
            fifo_register(fifo_registers_previous[fifo_index + 1], INVALID_JOB_ID, new_job_id, 
                          fifo_registers_previous[fifo_index],
                          data_select_signals[fifo_index], &fifo_registers_current[fifo_index]);
            
            if (data_select_signals[fifo_index] == W_DISABLE) {
                *top_job_id = fifo_registers_previous[0];
            } else if (data_select_signals[fifo_index] == LD_SELECT) {
                *top_job_id = fifo_registers_previous[1];
            } else if (data_select_signals[fifo_index] == NEW_D_SELECT) {
                *top_job_id = new_job_id;
            } else {
                *top_job_id = INVALID_JOB_ID;
            }

        } else if (fifo_index == JOBS_PER_MACHINE - 1) {
            
            fifo_register(INVALID_JOB_ID, fifo_registers_previous[fifo_index - 1], new_job_id, 
                          fifo_registers_previous[fifo_index],
                          data_select_signals[fifo_index], &fifo_registers_current[fifo_index]);
        } else {

            fifo_register(fifo_registers_previous[fifo_index + 1], fifo_registers_previous[fifo_index - 1], 
                          new_job_id, fifo_registers_previous[fifo_index],
                          data_select_signals[fifo_index], &fifo_registers_current[fifo_index]);
        }
    }

    if (new_job_id != INVALID_JOB_ID) {
        *fifo_entry_count += 1;
     }

    if (pop) {
        *popped_job_id = fifo_registers_previous[0];
        *fifo_entry_count -= 1;
    } else {
        *popped_job_id = INVALID_JOB_ID;
    }

    if (*fifo_entry_count == JOBS_PER_MACHINE) {
        *full = 1;
    } else {
        *full = 0;
    }

fifo_read: for (vf_index_t fifo_index = 0; fifo_index < JOBS_PER_MACHINE; fifo_index++) {
        //#pragma HLS UNROLL

        fifo_registers_previous[fifo_index] = fifo_registers_current[fifo_index];
    }

#if VF_DEBUG
    std::cout << "\033[31m" << "HLS_PRINT: Data select signals: ";
    for (vf_index_t fifo_index = 0; fifo_index < JOBS_PER_MACHINE; fifo_index++) {
        std::cout << (int)data_select_signals[fifo_index] << " ";
    }
    std::cout << "\nHLS_PRINT: Fifo content: ";
    for (vf_index_t fifo_index = 0; fifo_index < JOBS_PER_MACHINE; fifo_index++) {
        std::cout << (int)fifo_registers_previous[fifo_index] << " ";
    }
    std::cout << "\n" << "\033[0m";
#endif
}


/*
 * This function implements fifo for all machines
 */
void fifo_all_machines(fifo_update_input_t *input, one_bit_t *pop,
                       data_selector_t data_select_signals[NUM_MACHINES][JOBS_PER_MACHINE], 
                       job_id_t *top_job_id, 
                       job_id_t *popped_job_id, one_bit_t *fifo_full) {

    static job_id_t fifo_registers_current[NUM_MACHINES][JOBS_PER_MACHINE] = {0};
    static job_id_t fifo_registers_previous[NUM_MACHINES][JOBS_PER_MACHINE] = {0};
    //static one_bit_t reset[NUM_MACHINES] = {0}; - Not needed until INVALID_JOB_ID is 0
    static job_id_t fifo_entry_count[NUM_MACHINES] = {0};

    //#pragma HLS array_partition variable=fifo_registers_current type=complete dim=0
    //#pragma HLS array_partition variable=fifo_registers_previous type=complete dim=0
    ////#pragma HLS array_partition variable=reset type=complete dim=0
    //#pragma HLS array_partition variable=fifo_entry_count type=complete dim=0

fifo_machine: 
    for (machine_id_t machine = 0; machine < NUM_MACHINES; machine++) {
        //#pragma HLS UNROLL
         fifo(input[machine].new_job_id, pop[machine], data_select_signals[machine],
              fifo_registers_current[machine], fifo_registers_previous[machine],
              //&reset[machine], 
              &fifo_entry_count[machine], 
              &top_job_id[machine], &popped_job_id[machine],
              &fifo_full[machine]);
    }

}

/*
 * This function is used to init the data selector output array
 */
inline void data_selector_output_init(data_selector_t* data_selector_output) {

ds_output_init: for (memory_length_t fifo_index = 0; fifo_index < JOBS_PER_MACHINE; fifo_index++) {
                    //#pragma HLS UNROLL
                    data_selector_output[fifo_index] = W_DISABLE;
    }
}

/*
 * This function implements data_selector_output_init for all machines
 */
void data_selector_output_init_all_machines(data_selector_t data_selector_output[NUM_MACHINES][JOBS_PER_MACHINE]) {

ds_output_init_machines: 
    for (machine_id_t machine = 0; machine < NUM_MACHINES; machine++) {
        
        //#pragma HLS UNROLL
        data_selector_output_init(data_selector_output[machine]);

    }
}


/*
 * This function is the top module for virtual fifo
 * 
 * param[in] input  Input to the virtual FIFO of type fifo_update_input
 * param[in] pop    Pop signal to pop a FIFO
 * 
 * param[out] top_job_id      Job ID present at the top of the FIFO
 * param[out] popped_job_id   Job ID present popped out of the FIFO
 * param[out] fifo_full       Fifo Full signal 
 */
void virtual_fifo(fifo_update_input_t *input, one_bit_t *pop,
                  job_id_t *top_job_id, job_id_t *popped_job_id,
                  one_bit_t *fifo_full) {
#if VF_TOP 
    //#pragma HLS INTERFACE m_axi port=input bundle=gmem0
    //#pragma HLS INTERFACE m_axi port=top_job_id bundle=gmem1
    //#pragma HLS INTERFACE m_axi port=popped_job_id bundle=gmem2
    //#pragma HLS INTERFACE m_axi port=fifo_full bundel=gmem3
    //#pragma HLS INTERFACE m_axi port=pop bundle=gmem4
#endif 

    data_selector_t data_selector_output[NUM_MACHINES][JOBS_PER_MACHINE] = {W_DISABLE};
    /* Temporary space holders of input and pop for pipelined implementation - Cannot be removed if pipelined
       implementation is required */
    fifo_update_input_t input_temp[NUM_MACHINES]; 
    one_bit_t pop_temp[NUM_MACHINES];
    
    //#pragma HLS array_partition variable=data_selector_output type=complete dim=0
    //#pragma HLS array_partition variable=input_temp type=complete dim=0
    //#pragma HLS array_partition variable=pop_temp type=complete dim=0

   // //#pragma HLS pipeline //if this pragma can be removed, input_temp and pop_temp arrays can be removed - Not advised - II of 1 could not be reached
   //#pragma HLS dataflow

    //initialize data selector and fifo modules
    //data_selector_output_init_all_machines(data_selector_output); - not required since each data select is assigned a value
    data_selector_all_machines(input, pop, data_selector_output,
                               input_temp, pop_temp);
    fifo_all_machines(input_temp, pop_temp, data_selector_output, top_job_id,
                      popped_job_id, fifo_full);

}